version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app/deploy


# CodeDeploy에서 EC2로 넘겨준 파일들을 모두 ec2-user권한을 가지게 한다.
permissions: 
   - object: /home/ec2-user/app/deploy
    pattern: "**"
    owner: ec2-user
    group: ec2-user


# ApplicationStart 단계에서 StartDeploy.sh를 실행시킴.
hooks:
 ApplicationStart:
    - location: script/StartDeploy.sh
      runas: ec2-user
