# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

# main branche로 push나 pr 날릴때 마다 이벤트 발생
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    
    # aws 자격증명 구성
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
         AWS_ACCESS_KEY_ID : ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY_ID : ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
         aws-region: ap-northeast-2

    - name: Grant execute permission for gradlew
      run : chmod +x gradlew
   
      
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
      
    
    # 전송할 파일을 담을 디렉토리 생성
    - name : Make Directory for deliver
      run : mkdir deploy
      
    # Jar 파일을 Copy
    - name : Copy Jar
      run : cp ./build/libs/*.jar ./deploy/
      
    # zip 파일로 압축하기
    - name: Create ZIP file
      run: zip -r ./springboot-intro-build.zip ./deploy

    # ZIP 파일을 S3 버킷에 업로드
    - name: Upload ZIP file to S3
      run: aws s3 cp ./springboot-intro-build.zip s3://spring-test-buckett/springboot-intro-build.zip


    # s3 버킷으로 copy
    - name : Copy to AWS s3 buket
      env :
        AWS_ACCESS_KEY_ID : ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY_ID : ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
      run : |
        aws s3 cp \ 
        -- region ap-northeast-2 \
        -- acl private \            # 업로드한 파일의 접근 권한을 "private"로 설정 (즉, 소유자만 읽을 수 있도록 함)
        -- ./spring-test-buckett.zip s3://spring-test-buckett/      # s3 버킷의 정보를 지정
    
    
      
